name: CIT Kafka

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

# See https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  kafka:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@6b3083af2869dc3314a0257a42f4af696cc79ba3
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

    - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753
      with:
        go-version: 1.20.x

    - name: Run kafka integration tests
      run: bash scripts/kafka-integration-test.sh

    - name: Output Kafka logs
      run: docker logs "${{ job.services.kafka.id }}"
      if: ${{ failure() }}

    services:
      zookeeper:
        image: bitnami/zookeeper
        ports:
          - 2181:2181
        options: >-
          --health-cmd "echo mntr | nc -w 2 -q 2 localhost 2181"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          ALLOW_ANONYMOUS_LOGIN: yes
      kafka:
        image: bitnami/kafka:3.1.0
        ports:
          - 9092:9092
        options: >-
          --health-cmd "kafka-broker-api-versions.sh --version"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
          ALLOW_PLAINTEXT_LISTENER: yes
          KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
